<ul class="dropdown-menu">
    <li><a href="/">AX5UI</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="/ax5core">ax5core</a></li>
    <li><a href="/ax5ui-mask">ax5ui-mask</a></li>
    <li><a href="/ax5ui-dialog">ax5ui-dialog</a></li>
    <li><a href="/ax5ui-toast">ax5ui-toast</a></li>
    <li><a href="/ax5ui-modal">ax5ui-modal</a></li>
    <li><a href="/ax5ui-calendar">ax5ui-calendar</a></li>
    <li><a href="/ax5ui-picker">ax5ui-picker</a></li>
    <li><a href="/ax5ui-formatter">ax5ui-formatter</a></li>
    <li><a href="/ax5ui-menu">ax5ui-menu</a></li>
    <li><a href="/ax5ui-media-viewer">ax5ui-media-viewer</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="https://www.axisj.com">axisj.com</a></li>
</ul>